"""Package metadata for TriCoder."""
__version__ = "1.2.7"
__author__ = "Jiri Otoupal"
__email__ = "j.f.otoupal@gmail.com"
__license__ = "Non-Commercial License"
__copyright__ = "Copyright (c) 2024 Jiri Otoupal"
